Canary/Canary/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Canary.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

Canary/Canary/Controllers/CoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Canary.Controllers
{
    public class CoverController : Controller
    {
        //
        // GET: /Cover/
        public ActionResult Index()
        {
            return View();
        }
	}
}

Canary/Canary/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace Canary.Controllers
{
    public class HomeController : SiteBaseController
    {
        public ActionResult Index()
        {
            return View();

        }
        public ActionResult ToBeDeleted()
        {
            return View("ToBeDeleted");

        }
    }
}

Canary/Canary/Controllers/SiteBaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Canary.Controllers
{
    public class SiteBaseController : Controller
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
        }
	}
}

Canary/Canary/Controllers/_CarouselPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Canary.Common.Models;

namespace Canary.Controllers
{
    public class _CarouselPartialController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            var _carouselList = new List<CarouselInfo>();
            _carouselList.Add(new CarouselInfo
            {
                ImageCss = "text-left",
                CarouselHeaderText = "Example headline.",
                CarouselDescription = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                CarouselImageSrc = "CustomerSpecific/KHAN/Images/bigstock-Construction-Worker-At-Site.jpg"
            });
            _carouselList.Add(new CarouselInfo
            {
                ImageCss = "",
                CarouselHeaderText = "Another example headline.",
                CarouselDescription = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                CarouselImageSrc = "CustomerSpecific/KHAN/Images/construction-banner-blueprint.jpg"
            });
            _carouselList.Add(new CarouselInfo
            {
                ImageCss = "text-right",
                CarouselHeaderText = "One more for good measure.",
                CarouselDescription = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                CarouselImageSrc = "Resources/Images/default-c1.png"
            });
            return PartialView("_carousel", _carouselList);
        }
	}
}
namespace Canary.Common.Models
{
    public class CarouselInfo
    {
        public string CarouselHeaderText { get; set; }
        public string CarouselImageSrc { get; set; }
        public string CarouselDescription { get; set; }
        public string ImageCss { get; set; }
    }
}

Canary/Canary/Controllers/_MenuPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Canary.Common.CustomConfiguration;

namespace Canary.Controllers
{
    public class _MenuPartialController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return PartialView("_menu", CustomConfiguration.GetAvailableMenus());
        }
	}
}

Canary/Canary/Views/Contact/ContactUs.cshtml
<div id="contactus"  class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you within 2 business days." rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <div class="panel panel-default">
                    <div class="text-center header">Our Office</div>
                    <div class="panel-body text-center">
                        <h4>Address</h4>
                        <div>
                            2217 Washington Blvd<br />
                            Washington DC<br />
                            #(703) 1234 1234<br />
                            service@company.com<br />
                        </div>
                        <hr />
                        <div id="map1" class="map">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">
    jQuery(function ($) {
        function init_map1() {
            var myLocation = new google.maps.LatLng(38.885516, -77.09327200000001);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map1"),
                mapOptions);
            marker.setMap(map);
        }
        init_map1();
    });
</script>

<style>
    .map {
        min-width: 300px;
        min-height: 300px;
        width: 100%;
        height: 100%;
    }

    .header {
        background-color: #F5F5F5;
        color: #36A0FF;
        height: 70px;
        font-size: 27px;
        padding: 10px;
    }
</style>

Canary/Canary/Views/Contact/Index.cshtml
<div id="contactus"  class="container pad-top">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you within 2 business days." rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <div class="panel panel-default">
                    <div class="text-center header">Our Office</div>
                    <div class="panel-body text-center">
                        <h4>Address</h4>
                        <div>
                            2217 Washington Blvd<br />
                            Washington DC<br />
                            #(703) 1234 1234<br />
                            service@company.com<br />
                        </div>
                        <hr />
                        <div id="map1" class="map">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">
    jQuery(function ($) {
        function init_map1() {
            var myLocation = new google.maps.LatLng(38.885516, -77.09327200000001);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map1"),
                mapOptions);
            marker.setMap(map);
        }
        init_map1();
    });
</script>

<style>
    .map {
        min-width: 300px;
        min-height: 300px;
        width: 100%;
        height: 100%;
    }

    .header {
        background-color: #F5F5F5;
        color: #36A0FF;
        height: 70px;
        font-size: 27px;
        padding: 10px;
    }

    .pad-top {
        padding-top:100px;
    }
</style>

Canary/Canary/Views/Cover/Index.cshtml
<link href="~/Resources/Styles/Preprocessors/Pages/cover.css" rel="stylesheet" />
<div class="container cover-body">
    <div class="site-wrapper" style="margin-top: 50px;">
        <div class="site-wrapper-inner">
            <h1 class="cover-heading"></h1>
            <div class="cover-container">
                <div class="inner cover">
                    <h1 class="cover-heading">Khan Construction</h1>
                    <p class="lead">
                        Khan Construction Company is a statewide general contracting firm, specializing in 
                        servicing residential, commercial and industrial turnkey projects. We do it all, 
                        from minor tenant improvements to major ground-up projects. 
                        We base our Finished Product on Quality.Value to the Customer is always stressed at Khan Construction Company. 
                        The backing behind our Guarantee is Experience, twenty-two years’ worth.
                        Our dedicated employees take pride in setting us apart with their commitment to integrity, 
                        professionalism and quality of service. 
                        We are the experts in commercial and retail projects, 
                        whether it’s a small office or new corporate headquarters. 
                        At Khan Construction, we take pride in our work and strive to earn the 
                        privilege of your business every step of the way. It’s that simple.
                    </p>
                    <p class="lead">
                        <a href="~/Home/Index" class="btn btn-lg btn-cover">Learn more</a>
                    </p>
                </div>
                <div class="mastfoot">
                    <div class="inner">
                        <p>Cover template for <a href="https://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo"></a>.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<style>
    html,
    body {
        height: 100%;
        background-color: #334;
        color: #fff;
    }
    .navbar{
        background-color: #334;
    }
    .navbar-light .navbar-brand,
    .navbar-light .navbar-toggler,
    .navbar-light .navbar-nav .open > .nav-link, 
    .navbar-light .navbar-nav .active > .nav-link,
    .navbar-light .navbar-nav .nav-link.open,
    .navbar-light .navbar-nav .nav-link {
        color: #fff;
    }
        .navbar-light .navbar-nav .nav-link:focus,
        .navbar-light .navbar-nav .nav-link:hover {
            color:bisque;
        }
</style>

Canary/Canary/Views/Home/Index.cshtml
@{  Html.RenderAction("Index", "_CarouselPartial");}

<div id="about" class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
</div>

Canary/Canary/Views/Shared/_carousel.cshtml
@using Canary.Common.Models;
@model List<CarouselInfo>

<link href="~/Resources/Styles/Preprocessors/Components/carousel.css" rel="stylesheet" />
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        @foreach(var carouselInfo in Model.Select((value, i) => new { i, value })){
        <div class="carousel-item @(@carouselInfo.i == 0 ? "active" : string.Empty) carousel-customHeight">
            <img class="first-slide" src="@carouselInfo.value.CarouselImageSrc" alt="First slide">
            <div class="container">
                <div class="carousel-caption d-none d-md-block @carouselInfo.value.ImageCss">
                    <h1>@carouselInfo.value.CarouselHeaderText</h1>
                    <p>@carouselInfo.value.CarouselDescription</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                </div>
            </div>
        </div>
        }
@*        <div class="carousel-item">
            <img class="second-slide" src="" alt="Second slide">
            <div class="container">
                <div class="carousel-caption d-none d-md-block">
                    <h1></h1>
                    <p></p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
                <div class="carousel-caption d-none d-md-block text-right">
                    <h1></h1>
                    <p></p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>*@
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<style>
    .carousel-customHeight {
        height:20rem;
    }
    .carousel-customHeight > img {
            height:20rem;
     }
</style>

Canary/Canary/Views/Shared/_footer.cshtml
<div class="footer" style="display:none;">
    <div class="right">
    </div>
    <div class="left">
    </div>
</div>

<style>
    .footer {
        height: 256px;
        background-color: #f9fbfb;
    }

        .footer .right {
            background-color: red;
            width: 50%;
            height: 256px;
            display: inline-block;
            float: right;
        }

        .footer .left {
            background-color: blue;
            width: 50%;
            height: 256px;
            display: inline-block;
            float: left;
        }
</style>

Canary/Canary/Views/Shared/_menu.cshtml
@using Canary.Common.CustomConfiguration.Menu;
@model MenuElementCollection

<nav class="navbar navbar-toggleable-md navbar-light fixed-top bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        @*<img src="~/CustomerSpecific/KHAN/Images/logo.png" />*@
        Khan Constructions
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            @foreach (MenuElement menu in Model)
            {
                <li class="nav-item @(@menu.IsActive ? "active" : string.Empty)">
                    <a class="nav-link" href="@menu.MenuSrc">@menu.Name<span class="sr-only">(current)</span></a>
            </li>
            }
        </ul>
        <div class="search-box">
            <form class="form-inline my-2 my-lg-0" style="display: none;">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
    <script src="~/Resources/Scripts/LocalFunctions.js"></script>
</nav>

Canary/Canary/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="~/Resources/Styles/site.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    @{  Html.RenderAction("Index","_MenuPartial"); }

    @RenderBody()

    @{ Html.RenderPartial("~/Views/Shared/_footer.cshtml"); }

    <!-- Bootstrap JS and other libs(Kept in body to avoid performance overload)-->
    <script src="~/Resources/Scripts/lib/jquery-3.2.1/jquery-3.2.1.min.js"></script>
    <script src="~/Resources/Scripts/lib/tether/tether.js"></script>
    <script src="~/Resources/Scripts/lib/BootStrap/js/bootstrap.min.js"></script>
</body>
</html>